module.exports = {
  PLAYLISTS_RECEIVED: "PLAYLISTS_RECEIVED",
  PLAYLIST_RECEIVED: "PLAYLIST_RECEIVED",
  SINGLE_PLAYLIST_RECEIVED: "SINGLE_PLAYLIST_RECEIVED",
  NEW_PLAYLIST_RECEIVED: "NEW_PLAYLIST_RECEIVED"
};
