module.exports = {
  USER_RECEIVED: "USER_RECEIVED",
  CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED",
  USER_SONGS_RECEIVED:  "USER_SONGS_RECEIVED",
  USER_PLAYLISTS_RECEIVED: "USER_PLAYLISTS_RECEIVED"
};
